# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('result', models.IntegerField()),
                ('correct', models.BooleanField()),
            ],
        ),
    ]
